### ISSUE TITLE
U2 PIN NAME ISSUE

### ISSUE THREAD

**Issue by sunzhongmeng** [akshaybaweja/component-tester-oled#1]
hello,I found the U2(LM4040) pin 1 named ANODE but the datasheet is assigned CATHODE.

**Comment by akshaybaweja** [comment]
Please refer to images below the U2 is the same as LM4040's datasheet. I have links to the datasheet and schematic below. Please cross verify.

[Link to Schematic](https://github.com/akshaybaweja/component-tester-oled/blob/master/Schematic.pdf)| [Link to Datasheet // Texas Instrument](https://www.ti.com/lit/ds/symlink/lm4040-n.pdf)
:-------------------------:|:-------------------------:
<img width="410" alt="Screen Shot 2020-07-08 at 12 41 24 PM" src="https://user-images.githubusercontent.com/12269575/86946420-581ea280-c118-11ea-96d8-e350453b1330.png"> |  <img width="410" alt="Screen Shot 2020-07-08 at 12 38 29 PM" src="https://user-images.githubusercontent.com/12269575/86946217-11c94380-c118-11ea-93ed-dda6b8e1caf6.png">

**Comment by sunzhongmeng** [comment]
> Please refer to images below the U2 is the same as LM4040's datasheet. I have links to the datasheet and schematic below. Please cross verify.
> 
> [Link to Schematic](https://github.com/akshaybaweja/component-tester-oled/blob/master/Schematic.pdf)	[Link to Datasheet // Texas Instrument](https://www.ti.com/lit/ds/symlink/lm4040-n.pdf)
> <img alt="Screen Shot 2020-07-08 at 12 41 24 PM" width="410" src="https://user-images.githubusercontent.com/12269575/86946420-581ea280-c118-11ea-96d8-e350453b1330.png">	<img alt="Screen Shot 2020-07-08 at 12 38 29 PM" width="410" src="https://user-images.githubusercontent.com/12269575/86946217-11c94380-c118-11ea-93ed-dda6b8e1caf6.png">

I mean the symbol of U2,the Pin 1 should named "CATHODE",and the Pin 2 name is "ANODE" as the datasheet .
